---
title: "COVID-19 in Mexico Project"
author: "Group 5 - Michelle Koh, Mileati Melese, Jiani Wang, Claire Williams, and Linlin Wu"
date: "`r Sys.Date()`"
output: html_document
---


```{r, read-config, echo=FALSE}
config <- config::get()
```

# Data Summary

```{r, load-data, echo=FALSE}
here::i_am("midterm_report.Rmd")
all_data <- read.csv(
  file = here::here("data/all_data.csv")
)

#Load the Table 1
demographic_table <- readRDS(
  here::here("output/demographic_table.rds")
)
demographic_table

obese_data <- read.csv(
  file = here::here("data/obese_data.csv")
)

not_obese_data <- read.csv(
  file = here::here("data/not_obese_data.csv")
)
```

# Graphical Analysis

## Figure 1

```{r, echo=FALSE}
graphical_analysis_fig1 <- readRDS(
  here::here("output/graphical_analysis_fig1.rds")
)
graphical_analysis_fig1
```

## Figure 2

```{r, echo=FALSE}
graphical_analysis_fig2 <- readRDS(
  here::here("output/graphical_analysis_fig2.rds")
)
graphical_analysis_fig2
```

## Figure 3

```{r, echo=FALSE}
graphical_analysis_fig3 <- readRDS(
  here::here("output/graphical_analysis_fig3.rds")
)
graphical_analysis_fig3
```


# Modeling


## Part 1

```{r, all_multinomial_tables_combined, echo=FALSE}
all_multinomial_tables_combined<- readRDS(
  file = here::here("output/all_multinomial_tables_combined.rds")
)
all_multinomial_tables_combined
```

## Part 2

```{r, echo=FALSE}
combined_tables <- readRDS(
  file = here::here("output/combined_table.rds")
)
combined_tables

aic_results <- readRDS(
  file = here::here("output/aic_results.rds")
)
aic_results
```

